### PR TITLE
feature: add ffmpeg binary to allow Playwright to record videos [sc-00]

### PR DESCRIPTION
**Pull request by Antoine-C**
Add ffmpeg linux binary to support Playwright video recording.
I will create another PR to trigger the release and create `101.0.4951.53-3`

### CODE REVIEW

**Comment by umutuzgur** [comment]
Are you gonna compress it with brotli?

**Comment by Antoine-C** [comment]
> Are you gonna compress it with brotli?

@umutuzgur I tried but it only saves us 1MB, not really worth it.

**Comment by umutuzgur** [comment]
Just curious, what was the compression level you used?

**Comment by Antoine-C** [comment]
I used the following command `brotli --best ffmpeg.tar.gz`, I haven't played with compression level as I assume "best" will do its best.

**Review by umutuzgur — APPROVED** [review]
LGTM

**Pull request merged**
